name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend
        run: docker build -t backend ./backend

      - name: Build Frontend
        run: docker build -t frontend .

      - name: Done
        run: echo "Build Successful"