name: Collab Canvas CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Build Docker backend image
      run: docker build -t collab-canvas-main2-backend ./backend

    - name: Build Docker frontend image
      run: docker build -t collab-canvas-main2-frontend .